/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CONTROLADOR.Controlador;
import MODELO.Modelo;
import MODELO.ModeloLibros;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Valeria
 */
public class CONSULTA_LIBROS extends javax.swing.JFrame {

    /**
     * Creates new form CONSULTA_LIBROS
     */
    
    DefaultTableModel modelotabla=new DefaultTableModel();
    Controlador c=new Controlador();
    
    int v=0;
    String Dispon="";
    File archivo2 = new File("Registro_Libros.obj");
    File archivo = new File("Registro_Prestamo.obj");
    ArrayList<Modelo> lista=new ArrayList<Modelo>();
    ArrayList<ModeloLibros> lista2= new ArrayList<ModeloLibros>();
    int cont=0;
    String NomBibli4;
    String ApeBibli4;
    int fila_seleccionada;
    String TituloJP;
    String AutorJP;
    String CodigoJP;
    String DisponibilidadJP;

    
    //metodo para hacer la disponibilidad
    /*public String Dispo(){
        try {
            lista=c.leerFS(archivo);
            lista2=c.leerFSLibros(archivo2);

            for (Modelo e:lista){
                for (ModeloLibros e2:lista2){
                   if (e.)) {
                       if(9); 
                   } else {
                       v=1;
                       break;
                       
                   }
                    break;
                }
                
                    
         
            }

            if (v>=1){
                Dispon="NO";
            }else{
                Dispon="SI";
            }
            lista.clear();
            lista2.clear();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CONSULTA_LIBROS.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CONSULTA_LIBROS.class.getName()).log(Level.SEVERE, null, ex);
        }
        return Dispon;
    }*/
    

    
    //metodo para limpiar tablas
    public void LimpiarTabla(){
        for (int i=0;i<TablaLibros.getRowCount();i++){
            modelotabla.removeRow(i);
            i-=1;
        }
    }

        
    public CONSULTA_LIBROS() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Consulta de Libros");
        modelotabla.addColumn("TÍTULO");
        modelotabla.addColumn("AUTOR");
        modelotabla.addColumn("CÓDIGO");
        //modelotabla.addColumn("DISPONIBLE");
        TablaLibros.setModel(modelotabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ACCIONES = new javax.swing.JPopupMenu();
        ACCIÓN = new javax.swing.JMenu();
        INFORMACIÓN = new javax.swing.JMenuItem();
        ACTUALIZAR = new javax.swing.JMenuItem();
        panelTranslucidoComplete1 = new org.edisoncor.gui.panel.PanelTranslucidoComplete();
        labelTask1 = new org.edisoncor.gui.label.LabelTask();
        panelRoundTranslucido1 = new org.edisoncor.gui.panel.PanelRoundTranslucido();
        jLabel2 = new javax.swing.JLabel();
        VOLVER_BTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaLibros = new javax.swing.JTable();
        LISTADO = new javax.swing.JButton();
        labelHeader1 = new org.edisoncor.gui.label.LabelHeader();
        TITULO = new org.edisoncor.gui.textField.TextField();
        jLabel1 = new javax.swing.JLabel();

        ACCIÓN.setText("ACCIÓN");

        INFORMACIÓN.setText("INFORMACIÓN");
        INFORMACIÓN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INFORMACIÓNActionPerformed(evt);
            }
        });
        ACCIÓN.add(INFORMACIÓN);

        ACTUALIZAR.setText("ACTUALIZAR");
        ACTUALIZAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACTUALIZARActionPerformed(evt);
            }
        });
        ACCIÓN.add(ACTUALIZAR);

        ACCIONES.add(ACCIÓN);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panelTranslucidoComplete1.setColorPrimario(new java.awt.Color(0, 204, 0));
        panelTranslucidoComplete1.setColorSecundario(new java.awt.Color(0, 51, 153));

        labelTask1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MULTIMEDIA/buscar.png"))); // NOI18N
        labelTask1.setText("LIBROS");
        labelTask1.setDescription("CONSULTA DE LIBROS");

        panelRoundTranslucido1.setColorPrimario(new java.awt.Color(0, 51, 102));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MULTIMEDIA/L_BUSCAR.png"))); // NOI18N
        jLabel2.setText(" ");

        VOLVER_BTN.setBackground(new java.awt.Color(153, 153, 153));
        VOLVER_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MULTIMEDIA/HOME.png"))); // NOI18N
        VOLVER_BTN.setText("VOLVER");
        VOLVER_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOLVER_BTNActionPerformed(evt);
            }
        });

        TablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaLibros.setComponentPopupMenu(ACCIONES);
        TablaLibros.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablaLibros);

        LISTADO.setBackground(new java.awt.Color(153, 153, 153));
        LISTADO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MULTIMEDIA/LISTA.png"))); // NOI18N
        LISTADO.setText("LISTADO");
        LISTADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LISTADOActionPerformed(evt);
            }
        });

        labelHeader1.setText("TITULO DEL LIBRO :");

        TITULO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TITULOKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TITULOKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelRoundTranslucido1Layout = new javax.swing.GroupLayout(panelRoundTranslucido1);
        panelRoundTranslucido1.setLayout(panelRoundTranslucido1Layout);
        panelRoundTranslucido1Layout.setHorizontalGroup(
            panelRoundTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRoundTranslucido1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelRoundTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRoundTranslucido1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(LISTADO)
                        .addGap(56, 56, 56)
                        .addComponent(VOLVER_BTN))
                    .addGroup(panelRoundTranslucido1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelRoundTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRoundTranslucido1Layout.createSequentialGroup()
                                .addComponent(labelHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TITULO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        panelRoundTranslucido1Layout.setVerticalGroup(
            panelRoundTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoundTranslucido1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelRoundTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(panelRoundTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VOLVER_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LISTADO, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRoundTranslucido1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("LIBROS EN STOCK");

        javax.swing.GroupLayout panelTranslucidoComplete1Layout = new javax.swing.GroupLayout(panelTranslucidoComplete1);
        panelTranslucidoComplete1.setLayout(panelTranslucidoComplete1Layout);
        panelTranslucidoComplete1Layout.setHorizontalGroup(
            panelTranslucidoComplete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucidoComplete1Layout.createSequentialGroup()
                .addGroup(panelTranslucidoComplete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTranslucidoComplete1Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTranslucidoComplete1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(panelRoundTranslucido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTranslucidoComplete1Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(labelTask1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelTranslucidoComplete1Layout.setVerticalGroup(
            panelTranslucidoComplete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucidoComplete1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(labelTask1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRoundTranslucido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTranslucidoComplete1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTranslucidoComplete1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VOLVER_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOLVER_BTNActionPerformed
        // TODO add your handling code here:
        INTERFAZ in=new INTERFAZ();
        in.setVisible(true);
        in.NomBibli1=NomBibli4;
        in.ApeBibli1=ApeBibli4;
        dispose();
    }//GEN-LAST:event_VOLVER_BTNActionPerformed

    private void TITULOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TITULOKeyReleased

        try {
            lista2=c.leerFSLibros(archivo2);
            this.LimpiarTabla();
            for (ModeloLibros e: lista2){
                if(e.BuscarLibro(TITULO.getText())){
                    String[] datos = new String[4];
                    datos[cont] = e.getTitulo();
                    cont += 1;
                    datos[cont] = e.getAutor();
                    cont += 1;
                    datos[cont] = e.getCodigo();
                    cont =0;
                    modelotabla.addRow(datos);   
                }
            }
            lista2.clear();
            //codigo para deshabilitar el boton en caso de que existan campos escritos en el textfile TITULO
            if(TITULO.getText().length()==0){
                LISTADO.setEnabled(true);
            }else{
                LISTADO.setEnabled(false);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CONSULTA_LIBROS.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CONSULTA_LIBROS.class.getName()).log(Level.SEVERE, null, ex);
        }
            



    }//GEN-LAST:event_TITULOKeyReleased

    private void TITULOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TITULOKeyTyped
        // TODO add your handling code here:
        //Accion para convertir todo lo que se escribe en mayuscula
        char c=evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String Buscador=(""+c).toUpperCase();
            c=Buscador.charAt(0);
            evt.setKeyChar(c);
        }
    }//GEN-LAST:event_TITULOKeyTyped

    private void LISTADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LISTADOActionPerformed
        // TODO add your handling code here:
        String[] datos= new String[3];
        
        try { 
            lista2=c.leerFSLibros(archivo2);
            for (ModeloLibros e: lista2){
                datos[cont]=e.getTitulo();
                cont+=1;
                datos[cont]=e.getAutor();
                cont+=1;
                datos[cont]=e.getCodigo();
                cont=0;
                modelotabla.addRow(datos);
                
            }
            lista.clear();
            LISTADO.setEnabled(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CONSULTA_LIBROS.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CONSULTA_LIBROS.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_LISTADOActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        NomBibli4=NomBibli4;
        ApeBibli4=ApeBibli4;
        REGISTRO_PRESTAMO v1= new REGISTRO_PRESTAMO();
        v1.NombBiblio.setText(NomBibli4+" "+ApeBibli4);

        
    }//GEN-LAST:event_formWindowActivated

    private void INFORMACIÓNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INFORMACIÓNActionPerformed
        // TODO add your handling code here:
        fila_seleccionada=TablaLibros.getSelectedRow();
        if (fila_seleccionada!=-1){
            TituloJP=(String) TablaLibros.getValueAt(fila_seleccionada, 0);
            AutorJP=(String) TablaLibros.getValueAt(fila_seleccionada, 1);
            CodigoJP=(String) TablaLibros.getValueAt(fila_seleccionada, 2);
            JOptionPane.showMessageDialog(null,"Los Datos son los siguientes: \n"+"Titulo del Libro: "+TituloJP+"\nAutor del Libro: "+AutorJP+"\nCodigo del Libro: "+CodigoJP,"INFORMACIÓN",JOptionPane.INFORMATION_MESSAGE,new ImageIcon("src/MULTIMEDIA/icon.png"));
        }else{
            JOptionPane.showMessageDialog(null, "No se selecciono ninguna fila", "AVISO", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/MULTIMEDIA/alerta.png"));
        }
    }//GEN-LAST:event_INFORMACIÓNActionPerformed

    private void ACTUALIZARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACTUALIZARActionPerformed
        // TODO add your handling code here:
        fila_seleccionada=TablaLibros.getSelectedRow();
        if (fila_seleccionada!=-1){
            INGRESO_L il=new INGRESO_L();
            il.setVisible(true);
            il.ActualizarBTN.setVisible(true);
            il.RegistrarLibro3.setEnabled(false);
            il.CODIGO.setText((String) TablaLibros.getValueAt(fila_seleccionada, 2));
            il.CODIGO.setEnabled(false);
            il.TITULO.setText((String) TablaLibros.getValueAt(fila_seleccionada, 0));
            il.AUTOR.setText((String) TablaLibros.getValueAt(fila_seleccionada, 1));
            INTERFAZ in=new INTERFAZ();
            in.NomBibli1=NomBibli4;
            in.ApeBibli1=ApeBibli4;
            dispose();
            
        }else{
            JOptionPane.showMessageDialog(null,"No se selecciono ninguna fila","AVISO",JOptionPane.INFORMATION_MESSAGE,new ImageIcon("src/MULTIMEDIA/alerta.png"));
        }
    }//GEN-LAST:event_ACTUALIZARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CONSULTA_LIBROS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CONSULTA_LIBROS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CONSULTA_LIBROS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CONSULTA_LIBROS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CONSULTA_LIBROS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu ACCIONES;
    private javax.swing.JMenu ACCIÓN;
    public javax.swing.JMenuItem ACTUALIZAR;
    public javax.swing.JMenuItem INFORMACIÓN;
    public javax.swing.JButton LISTADO;
    public org.edisoncor.gui.textField.TextField TITULO;
    public javax.swing.JTable TablaLibros;
    private javax.swing.JButton VOLVER_BTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private org.edisoncor.gui.label.LabelHeader labelHeader1;
    private org.edisoncor.gui.label.LabelTask labelTask1;
    private org.edisoncor.gui.panel.PanelRoundTranslucido panelRoundTranslucido1;
    private org.edisoncor.gui.panel.PanelTranslucidoComplete panelTranslucidoComplete1;
    // End of variables declaration//GEN-END:variables
}
