/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CONTROLADOR.Controlador;
import MODELO.Modelo;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Valeria
 */
public class CONSULTA_PRESTAMOS extends javax.swing.JFrame {

    /**
     * Creates new form CONSULTA_PRESTAMOS
     */
    
    DefaultTableModel modelotabla=new DefaultTableModel();
    Controlador c=new Controlador();
    File archivo = new File("Registro_Prestamo.obj");
    ArrayList<Modelo> lista= new ArrayList<Modelo>();
    int cont=0;
    int fila_seleccionada;
    String cedula="";
    String NomBibli3;
    String ApeBibli3;
    String CedulaJP;
    String NombreJP;
    String ApellidoJP;
    String TituloJP;
    String CodigoJP;
    String FechaJP;
    String EmpleadoJP;
    
    //metodo para limpiar tablas
    public void LimpiarTabla(){
        for (int i=0;i<TabPrestamos.getRowCount();i++){
            modelotabla.removeRow(i);
            i-=1;
        }
    }
    
    public CONSULTA_PRESTAMOS() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Ventana Principal");
        modelotabla.addColumn("Cedula");
        modelotabla.addColumn("Nombres");
        modelotabla.addColumn("Apellidos");
        modelotabla.addColumn("Titulo Libro");
        modelotabla.addColumn("Codigo");
        modelotabla.addColumn("Fecha");
        modelotabla.addColumn("Encargado del Registro");
        TabPrestamos.setModel(modelotabla);// Valeria: Cuando programes el boton de "consulta", la haces visible
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Acciones = new javax.swing.JPopupMenu();
        Accion = new javax.swing.JMenu();
        Actualizar = new javax.swing.JMenuItem();
        Borrar = new javax.swing.JMenuItem();
        Detalles = new javax.swing.JMenuItem();
        panelTranslucidoComplete1 = new org.edisoncor.gui.panel.PanelTranslucidoComplete();
        labelTask1 = new org.edisoncor.gui.label.LabelTask();
        jLabel1 = new javax.swing.JLabel();
        labelHeader1 = new org.edisoncor.gui.label.LabelHeader();
        NOM_LIBRO = new org.edisoncor.gui.textField.TextField();
        LIBROS_D = new javax.swing.JLabel();
        VOLVER_BTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        panel1 = new org.edisoncor.gui.panel.Panel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabPrestamos = new javax.swing.JTable();

        Accion.setText("Operación");

        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        Accion.add(Actualizar);

        Borrar.setText("Borrar");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });
        Accion.add(Borrar);

        Detalles.setText("Detalles");
        Detalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetallesActionPerformed(evt);
            }
        });
        Accion.add(Detalles);

        Acciones.add(Accion);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panelTranslucidoComplete1.setColorPrimario(new java.awt.Color(0, 204, 0));
        panelTranslucidoComplete1.setColorSecundario(new java.awt.Color(0, 51, 153));

        labelTask1.setText("LIBROS PRESTADOS");
        labelTask1.setDescription("CONSULTA DE LIBROS PRESTADOS");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setText("Busca los registros de algún prestamo.");

        labelHeader1.setText("NUMERO DE CEDULA:");

        NOM_LIBRO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NOM_LIBROKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NOM_LIBROKeyTyped(evt);
            }
        });

        LIBROS_D.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        LIBROS_D.setText("LIBROS PRESTADOS");

        VOLVER_BTN.setBackground(new java.awt.Color(153, 153, 153));
        VOLVER_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MULTIMEDIA/HOME.png"))); // NOI18N
        VOLVER_BTN.setText("VOLVER");
        VOLVER_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOLVER_BTNActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MULTIMEDIA/LIB_1.jpg"))); // NOI18N
        jLabel3.setText(" ");

        TabPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TabPrestamos.setComponentPopupMenu(Acciones);
        jScrollPane2.setViewportView(TabPrestamos);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout panelTranslucidoComplete1Layout = new javax.swing.GroupLayout(panelTranslucidoComplete1);
        panelTranslucidoComplete1.setLayout(panelTranslucidoComplete1Layout);
        panelTranslucidoComplete1Layout.setHorizontalGroup(
            panelTranslucidoComplete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucidoComplete1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTranslucidoComplete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTranslucidoComplete1Layout.createSequentialGroup()
                        .addComponent(labelHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTranslucidoComplete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelTranslucidoComplete1Layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(VOLVER_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NOM_LIBRO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelTranslucidoComplete1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(labelTask1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(108, 108, 108))
            .addGroup(panelTranslucidoComplete1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTranslucidoComplete1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LIBROS_D, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300))
        );
        panelTranslucidoComplete1Layout.setVerticalGroup(
            panelTranslucidoComplete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucidoComplete1Layout.createSequentialGroup()
                .addGroup(panelTranslucidoComplete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTranslucidoComplete1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTranslucidoComplete1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelTask1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(panelTranslucidoComplete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NOM_LIBRO, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VOLVER_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(LIBROS_D, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTranslucidoComplete1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTranslucidoComplete1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VOLVER_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOLVER_BTNActionPerformed
        // TODO add your handling code here:
        INTERFAZ in=new INTERFAZ();
        in.NomBibli1=NomBibli3;
        in.ApeBibli1=ApeBibli3;
        in.setVisible(true);
        dispose();
    }//GEN-LAST:event_VOLVER_BTNActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        // TODO add your handling code here:
        INTERFAZ in=new INTERFAZ();
        in.NomBibli1=NomBibli3;
        in.ApeBibli1=ApeBibli3;
        if (NOM_LIBRO.getText().length()==10 ){
            fila_seleccionada = TabPrestamos.getSelectedRow();
            if (fila_seleccionada!=-1){
                REGISTRO_PRESTAMO rp = new REGISTRO_PRESTAMO();
                rp.setVisible(true);
                rp.NomBibli2=NomBibli3;
                rp.ApeBibli2=ApeBibli3;
                rp.Actualizar.setVisible(true);
                rp.Registro_btn.setEnabled(false);
                rp.Cedula.setText((String) TabPrestamos.getValueAt(fila_seleccionada, 0));
                rp.Cedula.setEnabled(false);
                rp.Nombre.setText((String) TabPrestamos.getValueAt(fila_seleccionada, 1));
                rp.Apellido.setText((String) TabPrestamos.getValueAt(fila_seleccionada, 2));
                rp.T_Libro.setSelectedItem((String) TabPrestamos.getValueAt(fila_seleccionada, 3));
                rp.C_Libro.setText((String) TabPrestamos.getValueAt(fila_seleccionada, 4));
                rp.Fecha.setText((String) TabPrestamos.getValueAt(fila_seleccionada, 5));
                rp.NombBiblio.setText((String) TabPrestamos.getValueAt(fila_seleccionada, 6));
                rp.NombBiblio.setEnabled(false);
                dispose();
            }else{
                JOptionPane.showMessageDialog(null,"No se selecciono ninguna fila","AVISO",JOptionPane.INFORMATION_MESSAGE,new ImageIcon("src/MULTIMEDIA/alerta.png"));
            }
            
        }else{
            JOptionPane.showMessageDialog(null,"Ingrese todo el numero de cedula antes de continuar.","AVISO",JOptionPane.INFORMATION_MESSAGE,new ImageIcon("src/MULTIMEDIA/alerta.png"));
            NOM_LIBRO.setText("");
            
        }
        
    }//GEN-LAST:event_ActualizarActionPerformed

    private void NOM_LIBROKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NOM_LIBROKeyReleased
        
        try {
            lista=c.leerFS(archivo);
            this.LimpiarTabla();
            for (Modelo e: lista){
                if(e.BuscarPrestamo(NOM_LIBRO.getText())){
                    String[] datos = new String[7];
                    datos[cont] = e.getCedula();
                    cont += 1;
                    datos[cont] = e.getNombres();
                    cont += 1;
                    datos[cont] = e.getApellidos();
                    cont += 1;
                    datos[cont] = e.getTitulo_libro();
                    cont += 1;
                    datos[cont] = e.getCod_libro();
                    cont += 1;
                    datos[cont] = e.getFecha();
                    cont += 1;
                    datos[cont] = e.getEmpleado();
                    cont = 0;
                    modelotabla.addRow(datos);
                }
            //lista.clear();         
        }
        lista.clear();  
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CONSULTA_PRESTAMOS.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CONSULTA_PRESTAMOS.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_NOM_LIBROKeyReleased

    private void NOM_LIBROKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NOM_LIBROKeyTyped
        // TODO add your handling code here:
        //Accion para convertir todo lo que se escribe en mayuscula
        char c=evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String Buscador=(""+c).toUpperCase();
            c=Buscador.charAt(0);
            evt.setKeyChar(c);
        }
        //codigo para que solo acepte solo números enteros
        if (evt.getKeyChar()<'0'||evt.getKeyChar()>'9'){
            evt.consume();
        }
        //solo acepte 10 números
        if (NOM_LIBRO.getText().length()==10){
            evt.consume();
            
        }
    }//GEN-LAST:event_NOM_LIBROKeyTyped

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        // TODO add your handling code here:
        
        if (NOM_LIBRO.getText().length()==10){
            fila_seleccionada = TabPrestamos.getSelectedRow();
            if (fila_seleccionada != -1) {
                cedula = (String) TabPrestamos.getValueAt(fila_seleccionada, 0);
                try {

                    for (Modelo e : c.leerFS(archivo)) {
                        if (e.getCedula().equals(cedula)) {
                            continue;
                        } else {
                            lista.add(e);
                        }
                    }
                    c.BorrarFS(lista, archivo);
                    lista.clear();
                    INTERFAZ in=new INTERFAZ();
                    in.NomBibli1=NomBibli3;
                    in.ApeBibli1=ApeBibli3;
                    in.setVisible(true);
                    dispose();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CONSULTA_PRESTAMOS.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(CONSULTA_PRESTAMOS.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "No se selecciono ninguna fila", "AVISO", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/MULTIMEDIA/alerta.png"));
            }
            
        }else{
            JOptionPane.showMessageDialog(null,"Ingrese todo el numero de cedula antes de continuar.","AVISO",JOptionPane.INFORMATION_MESSAGE,new ImageIcon("src/MULTIMEDIA/alerta.png"));
            NOM_LIBRO.setText("");
        }
        
        
        
    }//GEN-LAST:event_BorrarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        NomBibli3=NomBibli3;
        ApeBibli3=ApeBibli3;
        REGISTRO_PRESTAMO v1= new REGISTRO_PRESTAMO();
        v1.NombBiblio.setText(NomBibli3+" "+ApeBibli3);

    }//GEN-LAST:event_formWindowActivated

    private void DetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetallesActionPerformed
        // TODO add your handling code here:
        INTERFAZ in=new INTERFAZ();
        in.NomBibli1=NomBibli3;
        in.ApeBibli1=ApeBibli3;
        fila_seleccionada=TabPrestamos.getSelectedRow();
        if (fila_seleccionada!=-1){
            CedulaJP=(String) TabPrestamos.getValueAt(fila_seleccionada, 0);
            NombreJP=(String) TabPrestamos.getValueAt(fila_seleccionada, 1);
            ApellidoJP=(String) TabPrestamos.getValueAt(fila_seleccionada, 2);
            TituloJP=(String) TabPrestamos.getValueAt(fila_seleccionada, 3);
            CodigoJP=(String) TabPrestamos.getValueAt(fila_seleccionada, 4);
            FechaJP=(String) TabPrestamos.getValueAt(fila_seleccionada, 5);
            EmpleadoJP=(String) TabPrestamos.getValueAt(fila_seleccionada, 6);
            JOptionPane.showMessageDialog(null,"La Información es la siguiente: \n\n"+
            "Cedula: "+CedulaJP+
            "\nNombre: "+NombreJP+
            "\nApellido: "+ApellidoJP+
            "\nTitulo del Libro: "+TituloJP+
            "\nCodigo de Libro: "+CodigoJP+
            "\nFecha del Préstamo: "+FechaJP+
            "\nEmpleado que Registro: "+EmpleadoJP,
            "INFORMACIÓN",JOptionPane.INFORMATION_MESSAGE,new ImageIcon("src/MULTIMEDIA/icon.png"));

        }else{
            JOptionPane.showMessageDialog(null, "No se selecciono ninguna fila", "AVISO", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/MULTIMEDIA/alerta.png"));

        }
    }//GEN-LAST:event_DetallesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CONSULTA_PRESTAMOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CONSULTA_PRESTAMOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CONSULTA_PRESTAMOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CONSULTA_PRESTAMOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CONSULTA_PRESTAMOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu Accion;
    public javax.swing.JPopupMenu Acciones;
    public javax.swing.JMenuItem Actualizar;
    public javax.swing.JMenuItem Borrar;
    private javax.swing.JMenuItem Detalles;
    private javax.swing.JLabel LIBROS_D;
    org.edisoncor.gui.textField.TextField NOM_LIBRO;
    javax.swing.JTable TabPrestamos;
    private javax.swing.JButton VOLVER_BTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private org.edisoncor.gui.label.LabelHeader labelHeader1;
    private org.edisoncor.gui.label.LabelTask labelTask1;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.PanelTranslucidoComplete panelTranslucidoComplete1;
    // End of variables declaration//GEN-END:variables
}
