/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CONTROLADOR.Controlador;
import MODELO.ModeloLibros;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Valeria
 */
public class INGRESO_L extends javax.swing.JFrame {

    /**
     * Creates new form INGRESO_L
     */
    ArrayList<ModeloLibros>lista2=new ArrayList<ModeloLibros>();
    //File archivo= new File("/home/usuario/Escritorio/SERIALIZABLE/TERCERO_SIS.obj");
    File archivo= new File("Registro_Libros.obj");
    Controlador c=new Controlador();
    String NomBibli5;
    String ApeBibli5;
    public INGRESO_L() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Ingreso de Libros Nuevos");
        ActualizarBTN.setVisible(false);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTranslucido1 = new org.edisoncor.gui.panel.PanelTranslucido();
        labelTask2 = new org.edisoncor.gui.label.LabelTask();
        jLabel1 = new javax.swing.JLabel();
        panelTranslucido6 = new org.edisoncor.gui.panel.PanelTranslucido();
        labelHeader10 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader11 = new org.edisoncor.gui.label.LabelHeader();
        labelHeader12 = new org.edisoncor.gui.label.LabelHeader();
        TITULO = new org.edisoncor.gui.textField.TextField();
        AUTOR = new org.edisoncor.gui.textField.TextField();
        CODIGO = new org.edisoncor.gui.textField.TextField();
        RegistrarLibro3 = new javax.swing.JButton();
        Volver3 = new javax.swing.JButton();
        ActualizarBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panelTranslucido1.setColorPrimario(new java.awt.Color(51, 204, 0));
        panelTranslucido1.setColorSecundario(new java.awt.Color(0, 153, 204));

        labelTask2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MULTIMEDIA/bloc.png"))); // NOI18N
        labelTask2.setText("LIBROS");
        labelTask2.setDescription("REGISTRO DE NUEVOS LIBROS");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Registre, los libros con los datos que se le piden");

        panelTranslucido6.setColorPrimario(new java.awt.Color(255, 153, 255));
        panelTranslucido6.setColorSecundario(new java.awt.Color(0, 204, 204));
        panelTranslucido6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MULTIMEDIA/fondo.jpg"))); // NOI18N

        labelHeader10.setText("TÍTULO:");

        labelHeader11.setText("AUTOR:");

        labelHeader12.setText("CÓDIGO:");

        TITULO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TITULOKeyTyped(evt);
            }
        });

        AUTOR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AUTORKeyTyped(evt);
            }
        });

        CODIGO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CODIGOKeyTyped(evt);
            }
        });

        RegistrarLibro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MULTIMEDIA/REG.png"))); // NOI18N
        RegistrarLibro3.setText("REGISTRAR");
        RegistrarLibro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarLibroActionPerformed(evt);
            }
        });

        Volver3.setBackground(new java.awt.Color(153, 153, 153));
        Volver3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MULTIMEDIA/HOME.png"))); // NOI18N
        Volver3.setText("VOLVER");
        Volver3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        ActualizarBTN.setBackground(new java.awt.Color(153, 153, 153));
        ActualizarBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MULTIMEDIA/actualizar.png"))); // NOI18N
        ActualizarBTN.setText("ACTUALIZAR");
        ActualizarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarBTNVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTranslucido6Layout = new javax.swing.GroupLayout(panelTranslucido6);
        panelTranslucido6.setLayout(panelTranslucido6Layout);
        panelTranslucido6Layout.setHorizontalGroup(
            panelTranslucido6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucido6Layout.createSequentialGroup()
                .addGroup(panelTranslucido6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTranslucido6Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addGroup(panelTranslucido6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelHeader12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelTranslucido6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelHeader10, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                .addComponent(labelHeader11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelTranslucido6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AUTOR, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelTranslucido6Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(RegistrarLibro3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Volver3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTranslucido6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ActualizarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        panelTranslucido6Layout.setVerticalGroup(
            panelTranslucido6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucido6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panelTranslucido6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHeader10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTranslucido6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelTranslucido6Layout.createSequentialGroup()
                        .addComponent(labelHeader11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(labelHeader12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTranslucido6Layout.createSequentialGroup()
                        .addComponent(AUTOR, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(panelTranslucido6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarLibro3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Volver3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ActualizarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTranslucido1Layout = new javax.swing.GroupLayout(panelTranslucido1);
        panelTranslucido1.setLayout(panelTranslucido1Layout);
        panelTranslucido1Layout.setHorizontalGroup(
            panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucido1Layout.createSequentialGroup()
                .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTranslucido1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTask2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelTranslucido1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(panelTranslucido6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        panelTranslucido1Layout.setVerticalGroup(
            panelTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucido1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTask2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelTranslucido6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTranslucido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTranslucido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:
        INTERFAZ in=new INTERFAZ();
        in.NomBibli1=NomBibli5;
        in.ApeBibli1=ApeBibli5;
        in.setVisible(true);
        dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void RegistrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarLibroActionPerformed
        // TODO add your handling code here:
        if (TITULO.getText().isEmpty()||AUTOR.getText().isEmpty()||CODIGO.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "No se puede continuar.\nExisten campos vacios.");
        }else{
            ModeloLibros o1=new ModeloLibros(TITULO.getText(), AUTOR.getText(), CODIGO.getText());
            try {
                lista2=c.leerFSLibros(archivo);
                lista2.add(o1);
                c.EscribirFSLibros(lista2, archivo);
                INTERFAZ in=new INTERFAZ();
                in.NomBibli1=NomBibli5;
                in.ApeBibli1=ApeBibli5;
                in.setVisible(true);
                this.dispose();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(INGRESO_L.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(INGRESO_L.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_RegistrarLibroActionPerformed

    private void TITULOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TITULOKeyTyped
        // TODO add your handling code here:
         //Accion para convertir todo lo que se escribe en mayuscula
        char c=evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String Buscador=(""+c).toUpperCase();
            c=Buscador.charAt(0);
            evt.setKeyChar(c);
        }
    }//GEN-LAST:event_TITULOKeyTyped

    private void AUTORKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AUTORKeyTyped
        // TODO add your handling code here:
         //Accion para convertir todo lo que se escribe en mayuscula
        char c=evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String Buscador=(""+c).toUpperCase();
            c=Buscador.charAt(0);
            evt.setKeyChar(c);
        }
        //codigo para que solo acepte letras
        if ((evt.getKeyChar()<'A'||evt.getKeyChar()>'Z')&&(evt.getKeyChar()<'&'||evt.getKeyChar()>'&')&&(evt.getKeyChar()<' '||evt.getKeyChar()>' ')){
            evt.consume();
	}
    }//GEN-LAST:event_AUTORKeyTyped

    private void CODIGOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CODIGOKeyTyped
        // TODO add your handling code here:
         //Accion para convertir todo lo que se escribe en mayuscula
        char c=evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String Buscador=(""+c).toUpperCase();
            c=Buscador.charAt(0);
            evt.setKeyChar(c);
        }
        //solo acepte 6 caracteres
        if (CODIGO.getText().length()==6){
            evt.consume();
            
        }
    }//GEN-LAST:event_CODIGOKeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        NomBibli5=NomBibli5;
        ApeBibli5=ApeBibli5;
        REGISTRO_PRESTAMO v1= new REGISTRO_PRESTAMO();
        v1.NombBiblio.setText(NomBibli5+" "+ApeBibli5);
    }//GEN-LAST:event_formWindowActivated

    private void ActualizarBTNVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarBTNVolverActionPerformed
        // TODO add your handling code here:
        if (TITULO.getText().isEmpty()||AUTOR.getText().isEmpty()||CODIGO.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "No se puede continuar.\nExisten campos vacios.");
        }else{
            try {
                lista2=c.leerFSLibros(archivo);
                for (ModeloLibros e2: lista2){
                    if (e2.getCodigo().equals(CODIGO.getText())){
                        e2.setTitulo(TITULO.getText());
                        e2.setAutor(AUTOR.getText());
                    }
                }
                //Aqui escribo m nuevo array list modificado a mi archivo
                c.ActualizarFSLibros(lista2, archivo);
                lista2.clear();
                INTERFAZ in=new INTERFAZ();
                in.NomBibli1=NomBibli5;
                in.ApeBibli1=ApeBibli5;
                in.setVisible(true);
                dispose();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(INGRESO_L.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(INGRESO_L.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ActualizarBTNVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INGRESO_L.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INGRESO_L.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INGRESO_L.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INGRESO_L.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INGRESO_L().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public org.edisoncor.gui.textField.TextField AUTOR;
    public javax.swing.JButton ActualizarBTN;
    public org.edisoncor.gui.textField.TextField CODIGO;
    public javax.swing.JButton RegistrarLibro3;
    public org.edisoncor.gui.textField.TextField TITULO;
    private javax.swing.JButton Volver3;
    private javax.swing.JLabel jLabel1;
    private org.edisoncor.gui.label.LabelHeader labelHeader10;
    private org.edisoncor.gui.label.LabelHeader labelHeader11;
    private org.edisoncor.gui.label.LabelHeader labelHeader12;
    private org.edisoncor.gui.label.LabelTask labelTask2;
    private org.edisoncor.gui.panel.PanelTranslucido panelTranslucido1;
    private org.edisoncor.gui.panel.PanelTranslucido panelTranslucido6;
    // End of variables declaration//GEN-END:variables
}
